# This configuration runs each prompt through a series of example inputs and checks if they meet requirements.

prompts: [run_ts.ts:modify]
providers:
  [
    openai:gpt-3.5-turbo-0613,
    openai:gpt-4-0613,
    openai:completion:gpt-3.5-turbo-instruct,
  ]
tests:
  - description: Update the name of a person
    vars:
      messages:
        [
          {
            'sender': 'ian',
            'content':
              {
                'msgtype': 'org.boxel.card',
                'body': 'Can you change their name to Dave?',
                'instance':
                  {
                    'data':
                      {
                        'type': 'card',
                        'id': 'http://localhost:4201/drafts/Author/1',
                        'attributes':
                          { 'firstName': 'Bob', 'lastName': 'Enwunder' },
                        'meta':
                          {
                            'adoptsFrom':
                              { 'module': '../author', 'name': 'Author' },
                          },
                      },
                  },
              },
          },
        ]
      aibot_username: '@aibot:localhost'
    assert:
      - type: contains
        value: patch
  - description: Does a thing
    vars:
      chat_history: prompts/!UQVtOOiEkJROWvgicT:localhost.json
      cut_from_end: 1
      aibot_username: '@aibot:localhost'
    assert:
      - type: contains
        value: patch
