name: Deploy host
description: Deploy host with ember to S3 and Cloudfront

inputs:
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true

runs:
  using: composite
  steps:
    - name: Init
      uses: ./.github/actions/init

    - name: Set up env
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
        if [ "$INPUT_ENVIRONMENT" = "production" ]; then
          echo "AWS_ROLE_ARN=arn:aws:iam::120317779495:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-production" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E2DDEHLJXF5LQ8" >> $GITHUB_ENV
        elif [ "$INPUT_ENVIRONMENT" = "staging" ]; then
          echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-staging" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E35TXLK9HIMESQ" >> $GITHUB_ENV
        else
          echo "unrecognized environment"
          exit 1;
        fi

    - name: Download dist
      uses: actions/download-artifact@v3
      with:
        name: host-dist
        path: tmp/deploy-dist

    - name: Deploy
      shell: bash
      run: pnpm deploy:boxel-host ci:deploy --verbose

    - name: Send notification to Discord
      uses: ./.github/actions/discord-notification-deploy
      with:
        app: "boxel-host"
        status: ${{ github.action_status }}
        environment: ${{ inputs.environment }}
        webhook: ${{ inputs.discord_webhook }}
