name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:

env:
  PNPM_VERSION: 7.2.1

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint Addon
        run: pnpm run lint
        working-directory: addon
      - name: Lint Test App
        run: pnpm run lint
        working-directory: test-app
      - name: Lint Demo App
        run: pnpm run lint
        working-directory: demo-app
      - name: Run Tests
        run: pnpm run test:ember
        working-directory: test-app
