name: Manual Deploy [boxel]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

permissions:
  contents: read
  id-token: write

jobs:
  build-host:
    name: Build host
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build host
        uses: ./.github/actions/build-host
        with:
          environment: ${{ inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}

  deploy-host:
    name: Deploy host
    needs: [build-host, build-realm-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy host
        uses: ./.github/actions/deploy-host
        with:
          environment: ${{ inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}

  build-realm-server:
    name: Build realm-server
    uses: ./.github/workflows/waypoint-build.yml
    secrets: inherit
    with:
      app: "realm-demo"
      environment: ${{ inputs.environment }}

  deploy-realm-server:
    name: Deploy realm server to staging
    needs: [build-host, build-realm-server]
    uses: ./.github/workflows/waypoint-deploy.yml
    secrets: inherit
    with:
      app: "realm-demo"
      environment: ${{ inputs.environment }}
