name: Manual Deploy [realm-server]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

env:
  ENVIRONMENT: ${{ inputs.environment }}
  VOLTA_FEATURE_PNPM: 1

permissions:
  contents: read
  id-token: write

jobs:
  host-deploy:
    name: Deploy host
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy boxel-host if changes have happened
        uses: ./.github/actions/deploy-boxel-host
        with:
          environment: ${{ inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}

  realm-server-deploy:
    name: Deploy Realm Server
    needs: host-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy ${{ matrix.app }}
        uses: ./.github/actions/deploy-realm-server
        with:
          app_name: realm-demo
          environment: ${{ inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          production_waypoint_server_token: ${{ secrets.PRODUCTION_WAYPOINT_SERVER_TOKEN }}
          production_waypoint_server_address: ${{ secrets.PRODUCTION_WAYPOINT_SERVER_ADDR }}
          staging_waypoint_server_token: ${{ secrets.STAGING_WAYPOINT_SERVER_TOKEN }}
          staging_waypoint_server_address: ${{ secrets.STAGING_WAYPOINT_SERVER_ADDR }}
