name: CI

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-realm-server:
    uses: ./.github/workflows/deploy-realm-server.yml
    secrets: inherit
    with:
      environment: staging
